### PR TITLE
a few improvements to the image:

### PR DESCRIPTION
**Pull request by mierzwid**
* restore latest script
* better logging at startup
* reading only first line from passwords file to avoid reading new lines
* fixing issue with overriding sql-init template script in volume directory
* updating image to 2019-CU8-ubuntu-16.04

### CODE REVIEW

**Comment by thirdgen88** [comment]
Thank for these submissions..  I'll try to get to a review this weekend and then hopefully pull 'em in!

**Comment by thirdgen88** [comment]
@mierzwid: First question I have is about the movement of the `setup.sql` to the root..  I don't think there is an issue with putting it here--after all, many of the other resources are copied there already.  However, I don't see any pre-existing `/var/opt/mssql/setup.sql` file in the MS image.  Can you provide more insight on the overwrite you're referencing with this move?  I want to make sure I'm not overlooking anything...

**Comment by mierzwid** [comment]
@thirdgen88 since `setup.sql` is copied to `/var/opt/mssql/` when the image is built, when I mount a volume to the `/var/opt/mssql` at startup (my preference to keep all instance files on Docker volume), it gets simply swiped!

**Comment by thirdgen88** [comment]
I refreshed this repo recently with a fairly significant rework of both the build and the entrypoint/provisioning/restore logic.  I'm going to close this PR.

**Pull request closed without merging**
