### PR TITLE
fix restoring backup when filepath is not the default

### PR DESCRIPTION
**Pull request by alexrudd2**
MSSQL [backups](https://learn.microsoft.com/en-us/sql/relational-databases/backup-restore/backup-devices-sql-server?view=sql-server-ver16) contain filepaths in the backup file itself.  If a restore is attempted on a system without that filepath, it will fail.  For instance, restoring a backup made on Windows to this Ubuntu Docker image. :)

Using `sqlcmd` it is possible to query the backup file for the embedded filepaths.  Unfortunately the command outputs a "table" of data, but we can use `grep` to parse it.   This gives two filepaths (for data and logs) which can be passed into `sqlcmd` to restore properly.

Tested on `5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux` and `Docker version 25.0.0, build e758fe5`.

### CODE REVIEW

**Comment by thirdgen88** [comment]
Good catch here, this indeed does limit compatibility with bringing over backups from other installations.  In order to facilitate backups with multiple data/log files within, I ended up using [this T-SQL template](https://github.com/thirdgen88/mssql-docker/blob/main/shared/restore.sql) that gets completed and then executed [here](https://github.com/thirdgen88/mssql-docker/blob/3468d5ca09d6477904abc26a8c248ad36e07e0b9/shared/docker-entrypoint.sh#L61-L68).  These were merged in as part of #8.

**Comment by alexrudd2** [comment]
I like your approach of iterating through all the files, and using a more consistent SQL query rather than an ugly shell script.
<details><summary>old logs from me being dumb</summary>
However, it still doesn't work if the backup was created on Windows.

```
Database healthy, proceeding with provisioning...

/docker-entrypoint.sh: restoring /docker-entrypoint-initdb.d/backup.bak

Directory lookup for the file "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\backup.mdf" failed with the operating system error 2(The system cannot find the file specified.).

File 'backup' cannot be restored to 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\backup.mdf'. Use WITH MOVE to identify a valid location for the file.
```

 I don't know enough SQL to tell where it's going wrong, so these are wild guesses :)

Is `@FileType` not `D` and not `L`?  That would cause the `@PhysicalName` set up to fail.

Does it need to be `WITH MOVE` instead of `MOVE`?</details>

**Comment by alexrudd2** [comment]
Hang on, my Dockerfile is `kcollins/mssql:2019` and I only pulled `kcollins/mssql:latest` to test so this may well be user error :)

**Comment by alexrudd2** [comment]
It works!  Thank you very much.

Two comments:
(1) Is this check necessary to execute the restore?
```bash
if [ "${MSSQL_DATABASE}" ] && [ "${MSSQL_USER}" ] && [ "${MSSQL_PASSWORD}" ]
```

Those will be specified in the `.bak` file.

(2) 
```bash
ls /docker-entrypoint-initdb.d/ > /dev/null
```
With the `> /dev/null` this line is pretty useless.  Was it meant for debugging only?

(3)  EDIT: nevermind

**Comment by alexrudd2** [comment]
Closing in favor of https://github.com/thirdgen88/mssql-docker/pull/8

**Comment by thirdgen88** [comment]
> (1) Is this check necessary to execute the restore?
> 
> ```shell
> if [ "${MSSQL_DATABASE}" ] && [ "${MSSQL_USER}" ] && [ "${MSSQL_PASSWORD}" ]
> ```
> 
> Those will be specified in the `.bak` file.

No, not necessary for the restore, but if these are specified, the provisioning (via `setup.sql` template) will create and reassociate a SQL Login with a database user (from the backup, if applicable).

> (2)
> 
> ```shell
> ls /docker-entrypoint-initdb.d/ > /dev/null
> ```
> 
> With the `> /dev/null` this line is pretty useless. Was it meant for debugging only?

I have no idea why this is here, I'll remove it.

**Pull request closed without merging**
